name: taste_buddy
description: "Your personal cooking companion."

# Prevent accidental publishing to pub.dev.
publish_to: none

version: 1.0.0+1

environment:
  sdk: '^3.5.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  go_router: ^14.2.7
  collection: ^1.18.0
  fuzzywuzzy: ^1.2.0
  share_plus: ^10.0.2
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
